### ISSUE TITLE
Bug: File picker get wrong path on double click

### ISSUE THREAD

**Issue by Jackymancs4** [MarginallyClever/Robot-Overlord-App#126]
**Describe the bug**
As per discussion via Discord, I have managed to consistently replicate this.

**To Reproduce**
1. Click on any file picker and open the window
2. Double click on any file
3. Click on "Select"
4. See that the file path have the pattern "C:\Users\\{user}\RobotOverlord\Scene\\{file_name}\\{file_name}". Note the repeated file name.
5. Reopen the file selector.
6. See that the list is empty, while the folder does contain some files.

**Expected behavior**
The file path should point to the selected file.

**Platform (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - App Version 2.6.0 (built on ef8fb0c1b4d836e6d51e64e61d8db2f63c27b40d)

**Comment by Jackymancs4** [comment]
I confirm the issue is fixed!

**Comment by i-make-robots** [comment]
on double click the system that "jails" users to the scene path would try to open the file like a directory, cause and exception, and put the "file selection" dialog in a wierd state that produced the funky file/file name.
