### ISSUE TITLE
Improve "Edit arm" layout

### ISSUE THREAD

**Issue by Jackymancs4** [MarginallyClever/Robot-Overlord-App#129]
**Is your feature request related to a problem? Please describe.**
The Edit arm window is quite responsive, but I don't think it should be.
By default, it is very difficult to see the various file paths.

**Describe the solution you'd like**
My suggestions:
- [x] Set minimun width and height for the windows to something sensible like 800*600
- [x] Keep the row height fixed. Also keep the column width fixed, exept for "Mesh".
- [x] Align and pad "# Joint", "Texture" and "File"
- [x] Stretch "Texture" and "File" values

**Additional context**
Screens for reference:
![RobotOverlord_RJGCKEUUQt](https://github.com/MarginallyClever/Robot-Overlord-App/assets/6209647/5f0964c6-9ff3-4385-be3e-d0658c8dbe1c)
![RobotOverlord_7YsDy5rZPw](https://github.com/MarginallyClever/Robot-Overlord-App/assets/6209647/744c3d57-4711-49ea-825f-6fdbb5246f0f)
ture request here.

**Comment by i-make-robots** [comment]
Agreed.  I used a `GridLayout` for the table and it... doesn't scale well.  it doesn't allow column sizes, either.

**Comment by i-make-robots** [comment]
![image](https://github.com/MarginallyClever/Robot-Overlord-App/assets/1464454/c3de856f-7dd8-4d24-89cb-5b4878be8086)
like this?

**Comment by i-make-robots** [comment]
![image](https://github.com/MarginallyClever/Robot-Overlord-App/assets/1464454/3c3af7e6-d20a-451d-bdd3-6261bb16cebc)
![image](https://github.com/MarginallyClever/Robot-Overlord-App/assets/1464454/7f37575c-a58b-4e6d-b680-04df18e2bd98)
![image](https://github.com/MarginallyClever/Robot-Overlord-App/assets/1464454/4e884061-9f0f-41a4-a565-075b1c775274)
![image](https://github.com/MarginallyClever/Robot-Overlord-App/assets/1464454/24a137c4-ce90-4e91-8474-fdb5cea8fa19)
doesn't respect my minimum size settings....

**Comment by Jackymancs4** [comment]
Great improvement on the layout!

Only suggestion is to slighly increase the minum column size, so that the default values (with decimals) are still readable in "cramped" mode.

![RobotOverlord_f9I4VfchIs](https://github.com/MarginallyClever/Robot-Overlord-App/assets/6209647/f3971a0a-7edc-43e5-ac05-889e41ed6363)

**Comment by i-make-robots** [comment]
https://github.com/MarginallyClever/Robot-Overlord-App/commit/a7129e781ee9fd8b79a813935dfbe403a7a8f786#diff-1201499337140b977a2079d8e7197b647ed24756fb4d103f6679ec4d185044d0R36
You can see the ground work laid out here.  I don't know off the top of my head how to make it perfect. 
I welcome a PR to make this more perfect look & feel for you.

**Comment by Jackymancs4** [comment]
Yes, I reviewed those changes this morning. Yesterday I bet you would use a GridBagLayout!

Personally, I think setMinimumSize is just bugged to hell (https://stackoverflow.com/questions/10157954/java-swing-setmaximumsize-not-working & https://stackoverflow.com/questions/4061010/setmaximumsize-not-working-in-java)

>  I welcome a PR to make this more perfect look & feel for you.

I most likely will.
