### ISSUE TITLE
Opening Edit arm automatically moves arm components

### ISSUE THREAD

**Issue by Jackymancs4** [MarginallyClever/Robot-Overlord-App#130]
**Describe the bug**
This one may be my fault for not understanding the expected behavior.
When I create a robot Arm, opening the "Edit arm" panel for the first time jump start computations on unknown (to me) nature, that move the arm in a final resting position.

It is impossibile to restore the previous values as "Undo" does not work.

**To Reproduce**
1. Create new scene
2. Add Thor arm
3. Open the "Edit Arm"
4. See the arm start moving by itself

**Expected behavior**
Opening "Edit Arm" should allow me to edit the starting values of the arm.
The current "calculated" values should be editable in the "Control panel"

**Platform (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - App Version 2.6.0

**Additional context**
This behavior also happens with newly created arms.

**Comment by i-make-robots** [comment]
Thor and some of the downloadable arms do not have a 'target' entity.  when target is added the arm immediately tries to move to it.  but it is in the wrong place!

**Comment by i-make-robots** [comment]
so... is this considered fixed?

**Comment by Jackymancs4** [comment]
Yes. The PowerSwitchComponent and/or "Save" and"Cancel" in the arm editor ideas should be new feature request to be evaluated on their own.
