### ISSUE TITLE
Limit the number of Control Panels

### ISSUE THREAD

**Issue by Jackymancs4** [MarginallyClever/Robot-Overlord-App#146]
**Describe the bug**
There are no limit to how many Control Panels I can open.
I suggest limiting to only one per RobotComponent.
I usually open two of them for two different robot arms in the same scene.

**Comment by i-make-robots** [comment]
1. Limit 1 control panel per robot arm?
2. Limit 1 panel of any type per robot arm?

Currently I have No. 2 working in 1a5eb36c

**Comment by i-make-robots** [comment]
@Jackymancs4 do you still consider this unresolved?

**Comment by Jackymancs4** [comment]
I think No. 1 could be useful but I'll open a new issue if the need ever arise.
This issue is solved.
