### ISSUE TITLE
Message box with specific errors.

### ISSUE THREAD

**Issue by Jackymancs4** [MarginallyClever/Robot-Overlord-App#148]
**Is your feature request related to a problem? Please describe.**
If I set invalid DH parameters like D:0, R:0, A:0, T:200: Mx: 180, Mn:-180 then I click on Control Panel it asks me if the robot is initialized, but the Exception it throws knows better:
`java.lang.RuntimeException: Joint 0 is out of range.  200.0 not in [-180.0,180.0]`

**Describe the solution you'd like**
I think the error in the exception should be shown in message box in order to help to debug (human) errors.

**Describe alternatives you've considered**
Also I think this and pretty much all other Exceptions should be logged in the app log (log.txt).

**Comment by i-make-robots** [comment]
![image](https://github.com/MarginallyClever/Robot-Overlord-App/assets/1464454/fb09c397-6fed-472e-949c-469cbc1daf1b)
In this case I added bones with edit, deleted them, and then clicked control panel.  it should have said zero bones.
