### ISSUE TITLE
Feedback on the Grab button doing nothing

### ISSUE THREAD

**Issue by Jackymancs4** [MarginallyClever/Robot-Overlord-App#149]
**Is your feature request related to a problem? Please describe.**
It took me a while to understand "At present the gripper will only grab items that are between the jaw centers.", with the centers being the coords of the PoseComponent. (my meshes are pretty much never centered with the pose).
So clicking Grab just did nothing. When I got it, I still found difficult to position the box correctly.

**Describe the solution you'd like**
An indications (maybe a message box) that it did nothing because there was nothing to grab.

**Describe alternatives you've considered**
Add an option in the GripperConponent to draw a line between jaw centers, or 3 axial point (like the DH Parameters locator)
Also I think the gripper should be allowed to open/close empty handed. This should be another issue.

**Comment by i-make-robots** [comment]
At present the gripper can open and close empty-handed.

https://github.com/MarginallyClever/Robot-Overlord-App/assets/1464454/07e2c1d8-29ad-462d-8159-3322f7b7e838

illustrating the "grab line" is definitely an option.  
could be two grab lines, one from each jaw, and compare they hit the same item.

**Comment by Jackymancs4** [comment]
> At present the gripper can open and close empty-handed.

mmm... Mine doesn't. Only with the cube the claws move.
I'll prepare a video.

**Comment by Jackymancs4** [comment]
Video added.
