### ISSUE TITLE
A way to visually move each robot joint

### ISSUE THREAD

**Issue by jin-han** [MarginallyClever/Robot-Overlord-App#56]
current DH method -> (theta i) rotates along (z i-1) [previous frame]
The dragball is written so that it rotates along the current frame (z i) therefore doesn't work with this method.

method 2 -> (theta i) rotates along (z i) [current frame], it works with dragball but it will require a new transformation matrix.

**Comment by i-make-robots** [comment]
I mean maybe it could if the Gradient Descent understood it was not tracking to the last joint...
