### ISSUE TITLE
No response to WASD on keyboard

### ISSUE THREAD

**Issue by joladouille** [MarginallyClever/Robot-Overlord-App#67]
i can't find a build version of the software for my robot arm
wend i try to build myself i have no error (one warning bug it's ok) the soft run but all the cam control in the scene don't work
(WASDQE or mouse) and i can't move robot in the scene (like your youtube video) but just with the slider in the side bar

**Comment by i-make-robots** [comment]
Attach your log file please. Make sure you are running the development version of the app.

**Comment by i-make-robots** [comment]
renamed issue because not about building/compiling

**Comment by joladouille** [comment]
I don't know if it has anything to do with it, but it's on the top bar menu when I compile in the dev branch :
![image](https://user-images.githubusercontent.com/16057094/90000914-0e822400-dc91-11ea-8c6d-094de038dd1c.png)
the log :
[log.txt](https://github.com/MarginallyClever/Robot-Overlord-App/files/5061892/log.txt)

**Comment by i-make-robots** [comment]
Those messages appear because english values are missing from the translations in ./src/main/resources/languages/english.xml

In your log I see 

2020-08-12 11:43:12 InputManager start
2020-08-12 11:43:12 INPUT library path=null

I expected to see a list of all devices, their digital inputs, and their analog inputs.  So somehow the input manager is failing to find anything and silently failing.  That's new and exciting!

**Comment by i-make-robots** [comment]
Please get latest and try this fix.

**Comment by i-make-robots** [comment]
Found the possible fix here: https://www.codota.com/code/java/classes/net.java.games.input.ControllerEnvironment?snippet=5ce6feea2fd38000040b91fb

**Comment by joladouille** [comment]
the problem isn't fixed.
logs:
[log.txt](https://github.com/MarginallyClever/Robot-Overlord-App/files/5065134/log.txt)
the view moves with a ps3 controller (emulate xbox 360 controller with SCP server)
logs with the controller :
[log.txt](https://github.com/MarginallyClever/Robot-Overlord-App/files/5065149/log.txt)

**Comment by i-make-robots** [comment]
2020-08-12 21:09:29 Controller 0:Périphérique clavier PIH Keyboard

it's definitely finding your keyboard....  Can you try running unit test /src/test/java/JInputTest::detectSingleInputChange() ?  it watches your input devices and reports any changes.  This will tell us if it can see change events at all.

**Comment by joladouille** [comment]
i have this error in start :
```
août 12, 2020 9:50:08 PM net.java.games.input.ControllerEnvironment log
INFOS: Failed to initialize device Generic Virtual HID Driver because of: java.io.IOException: Failed to acquire device (8007001e)
```
but it work with my xbox controller

**Comment by i-make-robots** [comment]
2020-08-12 21:09:29 Controller 6:Generic Virtual HID Driver Unknown

Your system is detecting one HID device but it doesn't find a driver for that device and is getting confused.  Searching online I see a possible culprit is a WACOM tablet or an out of date device driver.
Do you have something like that?  Can you unplug the device and try again?  Maybe update the driver for that device?

**Comment by joladouille** [comment]
i have stop this driver and reboot my pc
when i try your test file nothing happen
no error and no input detection

**Comment by i-make-robots** [comment]
Make sure //@Test is not commented out at the start.  I have it that way because of a problem with Continuous Integration.

I will modify the test to run for ...10 seconds and quit automatically, that way it will satisfy both worlds a little.

**Comment by joladouille** [comment]
I think the test work because it detect my gamepad

**Comment by i-make-robots** [comment]
ok, but did it say anything when you typed WASD?

**Comment by joladouille** [comment]
Nothing

**Comment by i-make-robots** [comment]
that is super weird.  com.marginallyclever.robotOverlord.swingInterface.InputManager is the class that is *trying* to read your devices.  look in update() to see where each device is tested for changes.  Maybe from there with smart debugging you can find something that gives me a hint why it isn't working.  I don't know what more I can do from here, but I want to help.

**Comment by joladouille** [comment]
i don't know why but the middle click of the mouse work now
if i select somthing on the scene i can use the XYZ axis this the left click
the keyboard still not work but it's okay i can mouve with the mouse and my DS3 controller thx for your work and think's for your help 👍

**Comment by i-make-robots** [comment]
Good good np thank you.  if you find the answer please let me know ASAP.
