### ISSUE TITLE
Variable wrongly defined in Robot-Overlord windows start.bat

### ISSUE THREAD

**Issue by cad435** [MarginallyClever/Robot-Overlord-App#75]
**Describe the bug**
Original start.bat for windows won't start Robot-Overlord. It says " robot overlord found" but afterwards it says "unable to access jar file"

Fix:

Replace the "%Makelangelo%" in Line 56 with "%Robot-Overlord%" as this is the right variable name wich gets checked beforehand

**Comment by i-make-robots** [comment]
Fixed the version included in all future releases.  Thank you!
